name: draggable_builder
description: Add draggable item support to dynamically built scrollable containers like GridView and ListView in Flutter.
version: 2.0.0

repository: https://github.com/adbonnin/flutter_draggable_builder
issue_tracker: https://github.com/adbonnin/flutter_draggable_builder/issues

topics:
  - draggable
  - builder
  - gridview
  - listview

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
