name: widgetbook_workspace
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.11.0
  widgetbook_annotation: ^3.3.0
  draggable_builder:
    path: '../'
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  widgetbook_generator: ^3.10.0

flutter:
  uses-material-design: true
